name:     Uploading

on:
  push:
    push:
      branches:
        - main

jobs:
  upload_to_SF:
    name:           Testing upload to SourceForge
    runs-on:        ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          VER=$(echo '0.0.1')
          echo "U_VERSION=$VER" >> $GITHUB_ENV
          CNT=$(git rev-list HEAD --count)
          echo "U_COM_CNT=$CNT" >> $GITHUB_ENV

      - name: Prepare build
        run: |
          echo "version is ${{ env.U_VERSION }}"
          echo "commits number is ${{ env.U_COM_CNT }}"
          echo "Here is the content ${{ env.U_COM_CNT }}" > Upload-${{ env.U_VERSION }}-b${{ env.U_COM_CNT }}.txt
          pwd
          ls

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }} {% endraw %}
          known_hosts: unnecessary

      #- name: Adding Known Hosts
        #run: ssh-keyscan -H {% raw %}${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts

      - name: Copy release to SF
        run: rsync -avz ./Upload-${{ env.U_VERSION }}-b${{ env.U_COM_CNT }}.txt {% raw %}${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:{{ secrets.REMOTE_PATH }}{% endraw %}


