name:     Uploading

on:
  push:
    push:
      branches:
        - main

jobs:
  upload_to_SF:
    name:           Testing upload to SourceForge
    runs-on:        macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          VER=$(echo '0.0.1')
          echo "U_VERSION=$VER" >> $GITHUB_ENV
          CNT=$(git rev-list HEAD --count)
          echo "U_COM_CNT=$CNT" >> $GITHUB_ENV

      - name: Prepare build
        run: |
          echo "Here is the content ${{ env.U_COM_CNT }}" > Upload-${{ env.U_VERSION }}-b${{ env.U_COM_CNT }}.txt

      - name: Copy release to SF
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete
          RSYNC_TARGET: ${{ secrets.REMOTE_PATH }}
          RSYNC_SOURCE: Upload-${{ env.U_VERSION }}-b${{ env.U_COM_CNT }}.txt
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USER}}
          SSH_HOSTNAME: ${{secrets.SSH_HOST}}



