name:     Uploading

on:
  push:
    push:
      branches:
        - main

jobs:
  upload_to_SF:
    name:           Testing upload to SourceForge
    runs-on:        ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          VER=$(echo '0.0.1')
          echo "U_VERSION=$VER" >> $GITHUB_ENV
          CNT=$(git rev-list HEAD --count)
          echo "U_COM_CNT=$CNT" >> $GITHUB_ENV

      - name: Prepare build
        run: |
          echo "version is ${{ env.U_VERSION }}"
          echo "commits number is ${{ env.U_COM_CNT }}"
          echo "Here is the content ${{ env.U_COM_CNT }}" > Upload-${{ env.U_VERSION }}-b${{ env.U_COM_CNT }}.txt
          pwd
          ls

      - name: Copy release to SF
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete
          path: Upload-${{ env.U_VERSION }}-b${{ env.U_COM_CNT }}.txt
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST  }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}


